require 'resque'
require 'resque/fifo/constants'
require "redis"
require "redlock"
require 'xxhash'
require "resque/plugins/fifo/queue/version"
require "resque/plugins/fifo/server"
require "resque/plugins/fifo/extensions"
require "resque/plugins/fifo/queue/drain_worker"
require "resque/plugins/fifo/queue/manager"
require 'resque/plugins/fifo/worker'
